env: flex
runtime: nodejs
service: storefront-ui
automatic_scaling:
  min_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
resources:
  memory_gb: 2.3
handlers:
- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto
