env: standard
runtime: nodejs16
instance_class: F1
service: storefront-ui
inbound_services:
- warmup
automatic_scaling:
    min_idle_instances: 1
    min_instances: 1
handlers:
  - url: /.*
    secure: always
    script: auto