steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '--build-arg', 'ENV=$_ENV', 'gcr.io/$PROJECT_ID/storefront-ui:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/storefront-ui:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'storefront-ui'
  - '--image'
  - 'gcr.io/$PROJECT_ID/storefront-ui:$COMMIT_SHA'
  - '--region'
  - 'australia-southeast1'
images:
- 'gcr.io/$PROJECT_ID/storefront-ui:$COMMIT_SHA'
timeout: 1500s
