steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./build.sh']
    env:
    - 'ENV=$_ENV'
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: 1500s
