export const styles = {
  header: {
    height: "100px",
    display: "flex",
    flexDirection: "row",
    paddingTop: "10px",
    paddingBottom: "10px",
    // backgroundColor: "#f9f6f2",
    alignItems: "center",
  },
  Respheader: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingTop: "10px",
    paddingBottom: "10px",
    backgroundColor: "#f9f6f2",
    justifyContent: "space-between",
  },
  MainGrid: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  RespoMainGrid: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  Button: {
    color: "Black",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    "&:active": {
      display: "inline-block",
    },
  },
  ButtonR: {
    color: "Black",
    paddingLeft: "20px",
  },
  ButtonRTypo: {
    fontSize: "22px",
    fontWeight: "600",
  },
  LoginButton: {
    fontSize: "16px",
    fontWeight: "600",
    margin: "0px 0px 0px 10px",
    width: "100%",
    textAlign: "center",
    color: "black",
    padding: "10px 16px",
    border: "1.5px solid",
    borderRadius: "666px",
  },
  GetAccessTypo: {
    fontSize: "16px",
    fontWeight: "600",
    padding: "10px 16px",
    margin: "0px 0px 0px 10px",
    textAlign: "center",
    width: "100%",
    color: "white",
    backgroundColor: "#1C1B1F",
    border: "1.5px solid",
    borderRadius: "25px",
    "&:hover": {
      backgroundColor: "#1C1B1F",
    },
  },
  Login1: {
    width: "90%",
    color: "black",
    border: "1.5px solid",
    borderRadius: "35px",
    fontSize: "16px",
    fontWeight: "600",
    padding: "15px",
  },
  GetAccess1: {
    width: "90%",
    color: "white",
    background: "#1c1b1f",
    border: "1.5px solid",
    borderRadius: "35px",
    fontSize: "16px",
    fontWeight: "600",
    padding: "15px",
    marginTop: "25px",
    marginBottom: "20px",
    "&:hover": {
      backgroundColor: "#1c1b1f",
    },
  },
  LoginBox: {
    backgroundColor: "#f9f6f2",
    width: "529px",
    padding: "24px",
    borderRadius: "16px",
  },
  RespLoginBox: {
    borderRadius: "10px",
    p: 25,
  },
  TextFeild: {
    width: "100%",
    color: "#49454F",
    borderColor: "#49454F",
    borderRadius: "5px",
    marginBottom: "24px",
  },
  TextFeilds: {
    width: "100%",
    fontSize: "16px",
    fontWeight: "400",
    color: "#49454F",
    borderColor: "#49454F",
    borderRadius: "5px",
    marginBottom: "24px",
  },
  BoxSelector: {
    display: "flex",
    backgroundColor: "transparent",
    borderRadius: "10px",
    border: "1px solid rgba(28, 27, 31, 0.64)",
    marginBottom: "24px",
    padding: "6px 5px",
  },
};
