export const styles = {
  heading: {
    marginTop: "100px",
    color: "#1C1B1F",
    lineHeight: "normal",
    zIndex: "2",
    position: "relative",
  },
  Typography: {
    color: "rgba(28, 27, 31)",
    marginBottom: "50px",
    lineHeight: "normal",
    letterSpacing: "normal",
    zIndex: "2",
    position: "relative",
    width: "100%",
    opacity: "0.64",
  },
  CreatorButton: {
    width: { xs: "100%", sm: "auto" },
    backgroundColor: "#1C1B1F",
    color: "rgb(249, 246, 242)",
    padding: "20px 20px",
    margin: "initial",
    borderRadius: "40px",
    zIndex: "4",
    "&:hover": {
      backgroundColor: "#1C1B1F",
    },
  },
  LoginBox: {
    backgroundColor: "#f9f6f2",
    width: "500px",
    borderRadius: "10px",
    p: 25,
  },
  RespBox: {
    borderRadius: "10px",
    px: 25,
  },
  RespLoginBox: {
    borderRadius: "10px",
    paddingBottom: "30px",
    px: 25,
  },
  BoxSelector: {
    display: "flex",
    backgroundColor: "transparent",
    borderRadius: "10px",
    border: "1px solid rgba(28, 27, 31, 0.64)",
    marginBottom: "24px",
    padding: "6px 5px",
    width: "188px",
  },
};
