export const styles = {
  MainBox: {
    paddingTop: "30px",
    position: "relative",
    zIndex: "9",
  },
  ResponsMainBox: {
    borderRadius: "16px",
  },
  Heading: {
    padding: "50px 0 0 21px",
    color: "rgb(249, 246, 242)",
  },
  ResponsHeading: {
    color: "rgb(249, 246, 242)",
  },
  Texts: {
    color: "rgb(249, 246, 242)",
    paddingTop: "30px",
    paddingLeft: "60px",
    margin: 0,
  },
  ResponsText: {
    color: "rgb(249, 246, 242)",
    paddingTop: "30px",
  },
  circlecount: {
    width: "45px",
    height: "45px",
    borderRadius: "50%",
    border: "1px solid",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(249, 246, 242, 1)",
  },
  Respocirclecount: {
    // height: { xs: "35px", sm: "50px" },
    // width: { xs: "35px", sm: "50px" },
    width: "45px",
    height: "45px",
    fontSize: { xs: "25px", sm: "30px" },
    borderRadius: "50%",
    border: "1px solid",
    backgroundColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(249, 246, 242, 1)",
  },
  images: {
    width: "42%",
  },
  number: {
    color: "#fff",
    fontSize: "22px",
    width: "50px",
    height: "50px",
    border: "1px solid #fff",
    borderRadius: "50%",
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minWidth: "50px",
  },
  stickyText: {
    lineHeight: "unset",
    paddingLeft: "28px",
    margin: "0 auto 0 0",
    maxWidth: "517px",
  },
  homesec5: {
    paddingBottom: "250px",
    ["@media (min-width:1440px)"]: {
      paddingBottom: "100px",
    },
  },
};
