export const styles = {
  bannerText: {
    position: "absolute",
    right: "-20px",
    bottom: "2px",
    margin: " 0 auto",
    width: "45%",
    ["@media (max-width:1400px)"]: {
      bottom: "-16px",
    },
    ["@media (max-width:1145px)"]: {
      bottom: "-16px",
    },
    ["@media (max-width:767px)"]: {
      position: "unset",
      width: "100%",
    },
  },
  FirstList: {
    color: " #1C1B1F",
    fontSize: "48px",
    ["@media (max-width:1145px)"]: {
      fontSize: "42px",
    },
    ["@media (max-width:850px)"]: {
      fontSize: "28px",
    },
  },
  FirstPara: {
    opacity: "0.64",
    fontSize: "22px",
    padding: "0 0 22px 0px",
    color: " #1C1B1F",
    ["@media (max-width:1145px)"]: {
      fontSize: "18px",
    },
  },
  creator: {
    background: "#1C1B1F",
    borderRadius: " 666px",
    borderWidth: " 0px",
    borderColor: " initial",
    color: "#F9F6F2",
    width: " 170px",
    whiteSpace: "nowrap",
    cursor: "pointer",
    fontSize: "21px",
    fontWeight: "900",
    padding: "15px 0",
    textTransform: " initial",
    marginRight: "28px",
    "&:hover": {
      backgroundColor: "#1C1B1F",
    },
    ["@media (max-width:1145px)"]: {
      width: " 152px",
      fontSize: " 18px",
      fontWeight: "900",
      padding: "12px 0",
    },
  },
  brands: {
    background: "transparent",
    borderRadius: " 666px",
    borderWidth: " 0px",
    border: "1px solid #1C1B1F",
    color: "#1C1B1F",
    width: " 170px",
    whiteSpace: "nowrap",
    cursor: "pointer",
    fontSize: "21px",
    fontWeight: "900",
    padding: "15px 0",
    textTransform: " initial",
    ["@media (max-width:1145px)"]: {
      width: " 152px",
      fontSize: " 18px",
      fontWeight: "900",
      padding: "12px 0",
    },
  },
  LoginBox: {
    width: "500px",
    borderRadius: "10px",
    p: 25,
  },
  TextFeild: {
    width: "100%",
    color: "rgb(121, 116, 126)",
    borderRadius: "5px",
    marginBottom: "24px",
  },
  TextFeilds: {
    width: "100%",
    border: ".5px solid rgba(0, 0, 0, 0.4)",
    borderRadius: "5px",
    marginBottom: "24px",
  },
  TabSelector: {
    background: " transparent",
    borderRadius: "10px",
    border: "1px solid rgba(28, 27, 31, 0.64)",
    marginBottom: "24px",
    width: "250px",
  },
};
