export const pages = [
  { name: "Home", link: "/" },
  { name: "Brands", link: "/brands" },
  { name: "Shop", link: "/Shop" },
  { name: "Faq", link: "/Faq" },
];

export const brandList = [
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
  "brands name",
];

export const shopList = [
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
  "shop name",
];
