export const styles = {
  header: {
    display: "flex",
    flexDirection: "row",
    textAlign: "center",
    paddingTop: "14px",
    paddingBottom: "15px",
  },
  Respheader: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingTop: "14px",
    paddingBottom: "15px",
  },
  MainGrid: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  Button: {
    color: "Black",
    fontSize: "16px",
    fontWeight: "600",
  },
  Login: {
    color: "black",
    border: "1.5px solid",
    borderRadius: "25px",
    fontSize: "16px",
    fontWeight: "600",
  },
  Login1: {
    width: "100%",
    color: "black",
    border: "1.5px solid",
    borderRadius: "25px",
    fontSize: "16px",
    fontWeight: "600",
    marginBottom: "10px",
  },
  GetAccess: {
    color: "white",
    background: "black",
    border: "1.5px solid",
    borderRadius: "25px",
    fontSize: "16px",
    fontWeight: "600",
    "&:hover": {
      backgroundColor: "black",
    },
  },
  GetAccess1: {
    width: "100%",
    color: "white",
    background: "black",
    border: "1.5px solid",
    borderRadius: "25px",
    fontSize: "16px",
    fontWeight: "600",
    "&:hover": {
      backgroundColor: "black",
    },
  },
};
