export const styles = {
  header: {
    display: "flex",
    flexDirection: "row",
    paddingTop: "14px",
    paddingBottom: "15px",
    backgroundColor: "#f9f6f2",
  },
  Respheader: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingTop: "14px",
    paddingBottom: "15px",
    backgroundColor: "#f9f6f2",
    justifyContent: "space-between",
  },
  MainGrid: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  Button: {
    color: "Black",
    fontSize: "16px",
    fontWeight: "600",
  },
  ButtonR: {
    color: "Black",
    paddingLeft: "20px",
  },
  ButtonRTypo: {
    fontSize: "22px",
    fontWeight: "600",
  },
  Login: {
    color: "black",
    border: "1.5px solid",
    borderRadius: "25px",
    marginRight: "20px",
  },
  LoginTypo: {
    fontSize: "16px",
    fontWeight: "600",
    padding: "12px, 16px, 12px, 16px",
  },
  GetAccessTypo: {
    fontSize: "16px",
    fontWeight: "600",
    padding: "12px, 16px, 12px, 16px",
  },
  GetAccess: {
    color: "white",
    background: "black",
    border: "1.5px solid",
    borderRadius: "25px",
    "&:hover": {
      backgroundColor: "black",
    },
  },
  Login1: {
    width: "90%",
    color: "black",
    border: "1.5px solid",
    borderRadius: "35px",
    fontSize: "16px",
    fontWeight: "600",
    padding: "15px",
  },
  GetAccess1: {
    width: "90%",
    color: "white",
    background: "#1c1b1f",
    border: "1.5px solid",
    borderRadius: "35px",
    fontSize: "16px",
    fontWeight: "600",
    padding: "15px",
    marginTop: "25px",
    marginBottom: "20px",
    "&:hover": {
      backgroundColor: "#1c1b1f",
    },
  },
  LoginBox: {
    width: "500px",
    borderRadius: "10px",
    p: 25,
  },
  RespLoginBox: {
    borderRadius: "10px",
    p: 25,
  },
  TextFeild: {
    width: "100%",
    color: "rgb(121, 116, 126)",
    borderRadius: "5px",
    marginBottom: "24px",
  },
  TextFeilds: {
    width: "100%",
    border: ".5px solid rgba(0, 0, 0, 0.4)",
    borderRadius: "5px",
    marginBottom: "24px",
  },
  TabSelector: {
    background: " transparent",
    borderRadius: "10px",
    border: "1px solid rgba(28, 27, 31, 0.64)",
    marginBottom: "24px",
    width: "250px",
  },
};
